document.writeln("<SCRIPT type=text\/javascript>");
document.writeln("imgUrl1=\"\/img\/01.jpg\";\/\/就是这里 ");
document.writeln("imgtext1=\"胜利油田工程\" ");
document.writeln("imgLink1=escape(\"\"); ");
document.writeln("imgUrl2=\"\/img\/02.jpg\"; ");
document.writeln("imgtext2=\"新疆天然气工程\" ");
document.writeln("imgLink2=escape(\"\"); ");
document.writeln("imgUrl3=\"\/img\/03.jpg\"; ");
document.writeln("imgtext3=\"衡阳炼钢二分厂\" ");
document.writeln("imgLink3=escape(\"\"); ");
document.writeln("imgUrl4=\"\/img\/04.jpg\"; ");
document.writeln("imgtext4=\"广西石化\" ");
document.writeln("imgLink4=escape(\"\"); ");
document.writeln("");
document.writeln("");
document.writeln(" var focus_width=210");
document.writeln(" var focus_height=190");
document.writeln(" var text_height=24");
document.writeln(" var swf_height = focus_height+text_height");
document.writeln(" ");
document.writeln(" var pics=imgUrl1+\"|\"+imgUrl2+\"|\"+imgUrl3+\"|\"+imgUrl4");
document.writeln(" var links=imgLink1+\"|\"+imgLink2+\"|\"+imgLink3+\"|\"+imgLink4");
document.writeln(" var texts=imgtext1+\"|\"+imgtext2+\"|\"+imgtext3+\"|\"+imgtext4");
document.writeln(" ");
document.writeln(" document.write(\'<object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"http:\/\/fpdownload.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=6,0,0,0\" width=\"\'+ focus_width +\'\" height=\"\'+ swf_height +\'\">\');");
document.writeln(" document.write(\'<param name=\"allowScriptAccess\" value=\"sameDomain\"><param name=\"movie\" value=\"\/skin\/focus.swf\"><param name=\"quality\" value=\"high\"><param name=\"bgcolor\" value=\"#F0F0F0\">\');");
document.writeln(" document.write(\'<param name=\"menu\" value=\"false\"><param name=wmode value=\"opaque\">\');");
document.writeln(" document.write(\'<param name=\"FlashVars\" value=\"pics=\'+pics+\'&links=\'+links+\'&texts=\'+texts+\'&borderwidth=\'+focus_width+\'&borderheight=\'+focus_height+\'&textheight=\'+text_height+\'\">\');");
document.writeln(" document.write(\'<embed src=\"\/skin\/focus.swf\" wmode=\"opaque\" FlashVars=\"pics=\'+pics+\'&links=\'+links+\'&texts=\'+texts+\'&borderwidth=\'+focus_width+\'&borderheight=\'+focus_height+\'&textheight=\'+text_height+\'\" menu=\"false\" bgcolor=\"#F0F0F0\" quality=\"high\" width=\"\'+ focus_width +\'\" height=\"\'+ focus_height +\'\" allowScriptAccess=\"sameDomain\" type=\"application\/x-shockwave-flash\" pluginspage=\"http:\/\/www.macromedia.com\/go\/getflashplayer\" \/>\');  document.write(\'<\/object>\');");
document.writeln(" ");
document.writeln("");
document.writeln(" <\/SCRIPT>");
document.writeln("")