document.writeln("<table width=\"986\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("      <tr>");
document.writeln("        <td width=\"986\" height=\"110\" background=\"\/img\/1271061445.gif\"><div align=\"center\">");
document.writeln("          <TABLE cellSpacing=0 cellPadding=0 width=986 align=center border=0>");
document.writeln("                <TBODY>");
document.writeln("                <TR>");
document.writeln("                  <TD bgColor=#1B1B1F colSpan=6 height=2><\/TD>");
document.writeln("                <\/TR>");
document.writeln("                <TR>");
document.writeln("                  <TD width=268 height=79 rowSpan=3>");
document.writeln("                    <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>");
document.writeln("                      <TBODY>");
document.writeln("                      <TR><\/TR>");
document.writeln("                      <TR>");
document.writeln("                        <TD width=261 height=67> <\/TD>");
document.writeln("                      <\/TR>");
document.writeln("                    <TR><\/TR><\/TBODY><\/TABLE><\/TD>");
document.writeln("                  <TD width=468><\/TD>");
document.writeln("                  <TD class=bg width=33 ");
document.writeln("          background=\"\/img\/topl.jpg\"><\/TD>");
document.writeln("                  <TD class=style1 vAlign=top align=middle width=171 height=20>");
document.writeln("                    <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>");
document.writeln("                      <TBODY>");
document.writeln("                      <TR>");
document.writeln("                        <TD vAlign=center align=middle bgColor=#1B1B1F height=20><A ");
document.writeln("            href=\"\/\" class=a2 style6 ><FONT ");
document.writeln("                  color=#ffffff>简体中文<\/FONT><\/A> | <A class=a2 id=based><span class=\"style6\"><FONT ");
document.writeln("                  color=#ffffff>繁體中文<\/FONT><\/span><\/A>");
document.writeln("                          <SCRIPT language=Javascript ");
document.writeln("                  src=\"\/img\/southidcj2f.Js\"><\/SCRIPT>");
document.writeln("                       | <\/TD>");
document.writeln("                      <\/TR>");
document.writeln("                      <\/TBODY><\/TABLE><\/TD>");
document.writeln("                  <TD class=bg width=33 ");
document.writeln("          background=\"\/img\/topr.jpg\"><\/TD>");
document.writeln("                  <TD width=40 height=20><\/TD><\/TR>");
document.writeln("                <TR>");
document.writeln("                  <TD colSpan=2>");
document.writeln("                    <DIV align=right><\/DIV><\/TD>");
document.writeln("                  <TD align=middle>今天是");
document.writeln("                    <SCRIPT language=JavaScript>");
document.writeln("			today=new Date();");
document.writeln("			function initArray(){");
document.writeln("			this.length=initArray.arguments.length");
document.writeln("			for(var i=0;i<this.length;i++)");
document.writeln("			this[i+1]=initArray.arguments[i]  }");
document.writeln("			var d=new initArray(");
document.writeln("			\" 星期日\",");
document.writeln("			\" 星期一\",");
document.writeln("			\" 星期二\",");
document.writeln("			\" 星期三\",");
document.writeln("			\" 星期四\",");
document.writeln("			\" 星期五\",");
document.writeln("			\" 星期六\");");
document.writeln("			document.write(");
document.writeln("			\"<font color=#000000 style=\'font-size:11px;font-family: verdana\'> \",");
document.writeln("			today.getYear(),\"-\",");
document.writeln("			today.getMonth()+1,\"-\",");
document.writeln("			today.getDate(),\"\",");
document.writeln("			d[today.getDay()+1],");
document.writeln("			\"<\/font>\" ); ");
document.writeln("		<\/SCRIPT>");
document.writeln("                    <\/TD>");
document.writeln("                  <TD colSpan=2><\/TD><\/TR>");
document.writeln("                <TR>");
document.writeln("                  <TD vAlign=bottom colSpan=5 height=69>");
document.writeln("                    <TABLE height=30 cellSpacing=0 cellPadding=0 width=725 border=0>");
document.writeln("                      <TBODY>");
document.writeln("                      <TR>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("                          <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/\"><FONT ");
document.writeln("                  color=#ffffff>网站首页<\/FONT><\/A><\/DIV><\/TD>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("                          <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/about\/\"><FONT ");
document.writeln("                  color=#ffffff>公司概况<\/FONT><\/A><\/DIV><\/TD>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("                          <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/news\"><FONT ");
document.writeln("                  color=#ffffff>新闻中心<\/FONT><\/A><\/DIV><\/TD>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("                          <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/about\/About-37.html\"><FONT ");
document.writeln("                  color=#ffffff>应用案例<\/FONT><\/A><\/DIV><\/TD>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("                          <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/valve\/\"><FONT ");
document.writeln("                  color=#ffffff>产品展示<\/FONT><\/A><\/DIV><\/TD>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("                          <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/service\/\"><FONT ");
document.writeln("                  color=#ffffff>阀门知识<\/FONT><\/A><\/DIV><\/TD>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("                          <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/job\/\" style7><FONT ");
document.writeln("                  color=#ffffff>人才招聘<\/FONT><\/A><\/DIV><\/TD>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("                          <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/Contact.html\"><FONT ");
document.writeln("                  color=#ffffff>联系我们<\/FONT><\/A><\/DIV><\/TD>");
document.writeln("                        <TD vAlign=center align=middle width=78>");
document.writeln("            <DIV align=center><A class=a11 ");
document.writeln("                  href=\"\/msg.html\"><FONT ");
document.writeln("                  color=#ffffff>在线留言<\/FONT><\/A><\/DIV><\/TD><\/TR><\/TBODY><\/TABLE><\/TD><\/TR><\/TBODY>");
document.writeln("          <\/TABLE>");
document.writeln("        <\/div><\/td>");
document.writeln("      <\/tr>");
document.writeln("    <\/table>")